# Generated by Django 4.1.3 on 2022-12-10 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pcod', models.CharField(max_length=30)),
                ('pname', models.CharField(max_length=100)),
                ('pcat', models.CharField(max_length=50)),
                ('rate', models.IntegerField()),
                ('img', models.ImageField(upload_to='pic')),
            ],
        ),
    ]
